articles/urls.py
from django.urls import path
from .views import article_create_view,article_detail_view,article_search_view



app_name = 'articles'
urlpatterns = [
    path('',article_search_view,name='search'),
    path('create/',article_create_view,name='create'),
    path('<slug:slug>/',article_detail_view,name='detail'),
]

recipes/urls.py
from django.urls import path

from .views import (recipe_list_view,
                    recipe_detail_view,
                    recipe_create_view,
                    recipe_update_view,
                    recipe_detail_hx_view,
                    recipe_ingredient_update_hx_view,
                    recipe_delete_view,
                    recipe_ingredient_delete_view,
                    recipe_ingredient_image_upload_view,)


app_name = 'recipes'

urlpatterns = [
    path("",recipe_list_view,name='list'),
    path("create/",recipe_create_view,name='create'),
    
    path("hx/<int:parent_id>/ingredient/<int:id>/",recipe_ingredient_update_hx_view,name='hx-ingredient-detail'),
    path("hx/<int:parent_id>/ingredient/",recipe_ingredient_update_hx_view,name='hx-ingredient-create'),
    path("hx/<int:id>/",recipe_detail_hx_view,name='hx-detail'),
    
    path("<int:parent_id>/image-upload/",recipe_ingredient_image_upload_view),
    
    path("<int:parent_id>/ingredient/<int:id>/delete/",recipe_ingredient_delete_view,name='ingredient-delete'),
    path("<int:id>/delete/",recipe_delete_view,name='delete'),
    path("<int:id>/edit/",recipe_update_view,name='update'),
    path("<int:id>/",recipe_detail_view,name='detail'),
    
    
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_view
from articles.views import (article_create_view, article_detail_view)
from accounts.views import login_view,logout_view,register_view
from search.views import search_view

urlpatterns = [
    path('',home_view),
    path('pantry/recipes/',include('recipes.urls')),
    path('articles/',include('articles.urls')),
    path('search/',search_view,name='search'),
    path('admin/', admin.site.urls),
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register/',register_view,name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <link rel="stylesheet" href='{% static "recipes/recipes-htmx.css" %}'>
</head>
<body>
    <h1>Hello World</h1>
    {% include 'search/search-form.html' %}
    {% block content %}

    {% endblock %}


    <script>
        document.body.addEventListener("htmx:configRequest",(event)=>{
            event.detail.headers['X-CSRFToken'] = '{{csrf_token}}'
        })
    </script>

</body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}

<h1>{{title}} (id = {{id}}!)</h1>
<p>{{content}} (id = {{id}}!)</p>
<a href="{% url 'articles:create' %}">Create Article</a>
<ul>
    {% for x in object_list %}
        {% if x.title %}
            <li><a href="{{ x.get_absolute_url }}">{{x.title}}  -  {{x.content}}</a></li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock content %}

templates/image-form.html
{% extends "base.html" %}


{% block content %}

<form action="." method="POST" 
    hx-post="{{request.path}}"
    hx-encoding="multipart/form-data"
>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Upload Image</button>
</form>

{% endblock %}